---
name: foo-2 Fast Feedback

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - foo-2/**
  pull_request:
    branches:
      - main
    paths:
      - foo-2/**

permissions:
  contents: write
  id-token: write

jobs:
  version:
    uses: coreeng/p2p/.github/workflows/p2p-version.yaml@v1
    with:
      version-prefix: foo-2/v
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}

  fastfeedback:
    needs: [version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-fastfeedback.yaml@v1
    secrets:
      env_vars: ${{ secrets.env_vars }}
    with:
      app-name: foo-2
      version: ${{ needs.version.outputs.version }}
      working-directory: foo-2